### ISSUE TITLE
Boolean type check fails with Mongoid::Boolean returned

### ISSUE THREAD

**Issue by danijel** [mongoid-rspec/mongoid-rspec#136]
It have this kind of tests failing

it { should have_field(:something).of_type(Boolean).with_default_value_of(false) }
with
Expected Model to have field named "something" of type Boolean with default value of false, got field "something" of type Mongoid::Boolean

mongoid (4.0.0)
mongoid-rspec (2.0.0.rc1)
rspec (3.1.0)

**Comment by rodrigopinto** [comment]
@danijel You should use `Mongoid::Boolean` to compare the type. Like this:

```ruby
it { should have_field(:something).of_type(Mongoid::Boolean).with_default_value_of(false) }
```

**Comment by danijel** [comment]
@rodrigopinto thanks
you just made me have a "D'oh!" moment :-)

**Comment by johnnyshields** [comment]
@rodrigopinto I propose to reopen this issue, we should allow `of_type(Boolean)` to work here

**Comment by rodrigopinto** [comment]
Hey @johnnyshields, this library is specific to support mongoid tests, which at the time of `2015`(when the issue was opened), it supported the `Mongoid::Boolean` as a type and that is why I suggest that way in the comment.

I do not know the current mongoid versions how it works(I am not using mongo for long time already), might be a reason to open it again. Could share why we should support `of_type(Boolean)`?

**Comment by johnnyshields** [comment]
Thought about this further. So Mongoid DOES define Boolean here: https://github.com/mongodb/mongoid/blob/621294b9d4f38e2f0a32984bbb415d544bed437c/lib/mongoid/criteria/queryable/extensions.rb#L4

and this can be used in the type definition, however, since Ruby does not natively define `::Boolean` a better solution is to remove `::Boolean` from Mongoid.
